# Generated by Django 5.0.3 on 2024-04-26 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=20)),
                ('Firstname', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
