# Generated by Django 5.0.4 on 2024-04-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0002_remove_job_posted_date_job_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
